name: 'dbt_spark_sales'
version: '1.0'
profile: 'spark'

model-paths: ["models"]
seed-paths: ["seeds"]

models:
  dbt_spark_sales:
    staging:
      materialized: view
    marts:
      materialized: table
